listeners:
  default:
    type: tcp
    bind: 0.0.0.0:8883
    ssl: on
    cafile: ca.crt
    certfile: server.crt
    keyfile: server.key
sys_interval: 60
timeout-disconnect-delay: 2
auth:
  password-file: passwd
topic-check:
  enabled: True
  plugins:
    - topic_acl
    - topic_taboo
  acl:
    file: acl_config.yaml
persistence:
  file: test.db 
