vaibhavagg2:
  acl_publish:
    device1:
    - vaibhavagg2/hello
  acl_publish_all:
  - vaibhavagg2/config
  - vaibhavagg2/device1/#
  - vaibhavagg2/hello
  acl_subscribe:
    device1:
    - vaibhavagg2/device1/#
  acl_subscribe_all: []
  devices:
    device1:
      key: $5$rounds=535000$.Xn1A1tJ8VyScMri$bn0GPCvsjuR26WhmSAQDysBIP8ibZ0JCd3SWDBaCF/D
  password: $5$rounds=535000$kZPynOYcTUo7g5ZH$mlaArpp3Ahqi1ceJAuuH/Ar5pVRI14qjs8Ku9ACTvT6
